language: ruby
rvm:
  - 2.5
  - 2.6

#services:
#  - postgresql

addons:
  postgresql: "9.6  "

  
stage: test

before_install:
  - sudo apt-get install -y libxml2-dev unzip curl
  
script:
  - gem build `ls | grep gemspec`
  - gem install `ls | grep -e '.gem$'`
  - bundle exec rake db:create db:migrate
  - bundle exec rspec


jobs:
  include:
    - stage: gem release
      rvm: 2.5
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        api_key: $RUBYGEMS_KEY
        gemspec: burstflow.gemspec


